get_which <- function(chr = NULL, position = NULL, offsets = NULL) {
  if(is.null(position)) stop("Mandatory argument position is missing")
  if(is.null(chr)) stop("Mandatory argument chr is missing")
  if(is.null(offsets)) stop("Mandatory argument offsets is missing")

  if (chr == "1") return(RangesList('1'=IRanges(position-offsets,position+offsets)))
  if (chr == "2") return(RangesList('2'=IRanges(position-offsets,position+offsets)))
  if (chr == "3") return(RangesList('3'=IRanges(position-offsets,position+offsets)))
  if (chr == "4") return(RangesList('4'=IRanges(position-offsets,position+offsets)))
  if (chr == "5") return(RangesList('5'=IRanges(position-offsets,position+offsets)))
  if (chr == "6") return(RangesList('6'=IRanges(position-offsets,position+offsets)))
  if (chr == "7") return(RangesList('7'=IRanges(position-offsets,position+offsets)))
  if (chr == "8") return(RangesList('8'=IRanges(position-offsets,position+offsets)))
  if (chr == "9") return(RangesList('9'=IRanges(position-offsets,position+offsets)))
  if (chr == "10") return(RangesList('10'=IRanges(position-offsets,position+offsets)))
  if (chr == "11") return(RangesList('11'=IRanges(position-offsets,position+offsets)))
  if (chr == "12") return(RangesList('12'=IRanges(position-offsets,position+offsets)))
  if (chr == "13") return(RangesList('13'=IRanges(position-offsets,position+offsets)))
  if (chr == "14") return(RangesList('14'=IRanges(position-offsets,position+offsets)))
  if (chr == "15") return(RangesList('15'=IRanges(position-offsets,position+offsets)))
  if (chr == "16") return(RangesList('16'=IRanges(position-offsets,position+offsets)))
  if (chr == "17") return(RangesList('17'=IRanges(position-offsets,position+offsets)))
  if (chr == "18") return(RangesList('18'=IRanges(position-offsets,position+offsets)))
  if (chr == "19") return(RangesList('19'=IRanges(position-offsets,position+offsets)))
  if (chr == "20") return(RangesList('20'=IRanges(position-offsets,position+offsets)))
  if (chr == "21") return(RangesList('21'=IRanges(position-offsets,position+offsets)))
  if (chr == "22") return(RangesList('22'=IRanges(position-offsets,position+offsets)))
  if (chr == "X") return(RangesList('X'=IRanges(position-offsets,position+offsets)))
  if (chr == "Y") return(RangesList('Y'=IRanges(position-offsets,position+offsets)))
}
